

services:
  green-app:
    image:  maryam19455/lights:green-v1.0.0
    networks:
      - traffic-lights
  
  red-app:
    image:  maryam19455/lights:red-v1.0.0
    networks:
      - traffic-lights
  
  yellow-app:
    image:  maryam19455/lights:yellow-v1.0.0
    networks:
      - traffic-lights

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    depends_on:
      - red-app
      - yellow-app
      - green-app
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - traffic-lights

networks:
  traffic-lights:
    driver: bridge
