

services:
  green-app:
    image:  maryam19455/lights:green-v1.0.0
    ports:
      - 3001:80
    networks:
      - traffic-lights
  
  red-app:
    image:  maryam19455/lights:red-v1.0.0
    ports:
      - 3002:80
    networks:
      - traffic-lights
  
  yellow-app:
    image:  maryam19455/lights:yellow-v1.0.0
    ports:
      - 3003:80
    networks:
      - traffic-lights


networks:
  traffic-lights:
    driver: bridge
